#!groovy
/*
Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
*/
node {
  checkout scm
  // stage('Checkout') {
  //   git branch: 'kapil/centos', changelog: false, poll: false, url: 'http://github.com/mesosphere/mesos.git'
  // }

  sh 'mkdir -p .m2'
  def dockerArgs = "-e MESOS_TAG=${params.MESOS_TAG} -e MESOS_RELEASE=${params.MESOS_RELEASE}"
      dockerArgs = "${dockerArgs} -v=/etc/passwd:/etc/passwd"
      dockerArgs = "${dockerArgs} -v=/etc/group:/etc/group"
      dockerArgs = "${dockerArgs} -v=$PWD/.m2:$HOME/.m2

  stage('Build') {
    parallel centos7: {
      docker.image("mesos/packaging:centos7").inside(dockerArgs) {
        sh 'support/packaging/centos/build_rpm.sh'
      }
      archiveArtifacts artifacts: '**/*.rpm', fingerprint: true
    },

    centos6: {
      docker.image("mesos/packaging:centos6").inside(dockerArgs) {
        sh 'support/packaging/centos/build_rpm.sh'
      }
      archiveArtifacts artifacts: '**/*.rpm', fingerprint: true
    }
  }
}
