#!groovy
/*
Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
*/
node {
  checkout scm
  // stage('Checkout') {
  //   git branch: 'kapil/centos', changelog: false, poll: false, url: 'http://github.com/mesosphere/mesos.git'
  // }

  def dockerArgs = "-e MESOS_TAG=${params.MESOS_TAG} -e MESOS_RELEASE=${params.MESOS_RELEASE}"
      dockerArgs = "${dockerArgs} -v=/etc/passwd:/etc/passwd"
      dockerArgs = "${dockerArgs} -v=/etc/group:/etc/group"

  stage('Build') {
    parallel centos7: {
      docker.image("mesos/packaging:centos7").inside(dockerArgs) {
        sh '''#!/bin/bash
          whoami
          set -x
            MESOS_VERSION=${MESOS_TAG%[-]*}

            export HOME=$PWD
            mkdir -p $HOME/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

            cp support/packaging/common/* $HOME/rpmbuild/SOURCES
            cp support/packaging/centos/7/mesos.spec $HOME/rpmbuild/SPECS

            pushd $HOME/rpmbuild/SOURCES
            if [ "$MESOS_VERSION" = "$MESOS_TAG" ]; then
              wget -nv https://dist.apache.org/repos/dist/release/mesos/${MESOS_VERSION}/mesos-${MESOS_VERSION}.tar.gz
            else
              wget -nv https://dist.apache.org/repos/dist/dev/mesos/${MESOS_TAG}/mesos-${MESOS_VERSION}.tar.gz
            fi
            popd

            rpmbuild \
              --define "MESOS_VERSION $MESOS_VERSION" \
              --define "MESOS_RELEASE $MESOS_RELEASE" \
              -ba $HOME/rpmbuild/SPECS/mesos.spec
        '''
      }
      archiveArtifacts artifacts: '**/*.rpm', fingerprint: true
    },

    centos6: {
      docker.image("mesos/packaging:centos6").inside(dockerArgs) {
        sh '''#!/bin/bash
          whoami
          set -x
            MESOS_VERSION=${MESOS_TAG%[-]*}

            export HOME=$PWD
            mkdir -p $HOME/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

            cp support/packaging/common/* $HOME/rpmbuild/SOURCES
            cp support/packaging/centos/6/mesos.spec $HOME/rpmbuild/SPECS

            pushd $HOME/rpmbuild/SOURCES
            if [ "$MESOS_VERSION" = "$MESOS_TAG" ]; then
              wget -nv https://dist.apache.org/repos/dist/release/mesos/${MESOS_VERSION}/mesos-${MESOS_VERSION}.tar.gz
            else
              wget -nv https://dist.apache.org/repos/dist/dev/mesos/${MESOS_TAG}/mesos-${MESOS_VERSION}.tar.gz
            fi
            popd

            source scl_source enable devtoolset-3
            rpmbuild \
              --define "MESOS_VERSION $MESOS_VERSION" \
              --define "MESOS_RELEASE $MESOS_RELEASE" \
              -ba $HOME/rpmbuild/SPECS/mesos.spec
        '''
      }
      archiveArtifacts artifacts: '**/*.rpm', fingerprint: true
    }
  }
}
